server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.159.128:8848 #配置Nacos地址
        server-addr:  192.168.206.128:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'




