server:
  port: 8006


spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.159.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://192.168.1.4:8006/actuator/health



